/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    NavigationControls: typeof import('./../src/components/NavigationControls.vue')['default']
    PhoneForm: typeof import('./../src/components/PhoneForm.vue')['default']
    QuizOption: typeof import('./../src/components/QuizOption.vue')['default']
    QuizQuestion: typeof import('./../src/components/QuizQuestion.vue')['default']
    QuizResults: typeof import('./../src/components/QuizResults.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessMessage: typeof import('./../src/components/SuccessMessage.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
